#!/bin/bash

set -e

TAGS=(9 9.6 9.6.14)

# parse image name to get the repository name
TAG_START=$(expr index "${IMAGE_NAME}" :)
REPOSITORY_NAME=${IMAGE_NAME:0:TAG_START-1}

# tag and push image for each additional tag
for TAG in "${TAGS[@]}"; do
    docker tag ${IMAGE_NAME} ${REPOSITORY_NAME}:${TAG}
    docker push ${REPOSITORY_NAME}:${TAG}
done
