name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '14.23/**'
      - '15.17/**'
      - '16.13/**'
      - '17.9/**'
      - '18.3/**'
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-24.04]

    strategy:
      fail-fast: false
      matrix:
        version: [14.23-trixie, 15.17-trixie, 16.13-trixie, 17.9-trixie, 18.3-trixie]
        include:
          - version: 14.23-trixie
            docker-context: 14.23/debian/default
            docker-tags: |
              nicoherbigde/postgresql:14.23
              nicoherbigde/postgresql:14.23-trixie
          - version: 15.17-trixie
            docker-context: 15.17/debian/default
            docker-tags: |
              nicoherbigde/postgresql:15.17
              nicoherbigde/postgresql:15.17-trixie
          - version: 16.13-trixie
            docker-context: 16.13/debian/default
            docker-tags: |
              nicoherbigde/postgresql:16.13
              nicoherbigde/postgresql:16.13-trixie
          - version: 17.9-trixie
            docker-context: 17.9/debian/default
            docker-tags: |
              nicoherbigde/postgresql:17.9
              nicoherbigde/postgresql:17.9-trixie
          - version: 18.3-trixie
            docker-context: 18.3/debian/default
            docker-tags: |
              nicoherbigde/postgresql:18.3
              nicoherbigde/postgresql:18.3-trixie

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
